In [26]:
import pandas as pd
import numpy as np

In [27]:
resume_data = pd.read_excel('/content/feedbacks_with_gemini (1).xlsx')

In [28]:
resume_data

file_name           category  \
0   Peoplesoft Admin_G Ananda Rayudu.docx         Peoplesoft   
1      Peoplesoft Admin_AnubhavSingh.docx  Peoplesoft Resume   
2    Peoplesoft Admin_G Ananda Rayudu.doc  Peoplesoft Resume   
3         Peoplesoft Admin_Gangareddy.doc  Peoplesoft Resume   
4            Peoplesoft Admin_Murali.docx  Peoplesoft Resume   
..                                    ...                ...   
75             Sri Krishna S_Hexaware.doc            workday   
76                 Srikanth-Hexaware.docx            workday   
77                  SSKumar_Hexaware.docx            workday   
78           Venkateswarlu B_Hexaware.doc            workday   
79              Vinay Kumar_Hexaware.docx            workday   

                                                 text  original_word_count  \
0                                                 NaN                    1   
1   Anubhav Kumar Singh\t\t\n\n  To work in a glob...                  963   
2   Profile Summary:\t\t\t\t\t\t\t\t\t\t\n7+ years...                  987   
3   PeopleSoft Database Administrator\n           ...                  786   
4   Murali\n\nExperience Summary \n\nI have 6 year...                  619   
..                                                ...                  ...   
75  Workday Integration Consultant\n\nName        ...                  925   
76  Seeking suitable positions in Workday HCM  as ...                  899   
77  WORKDAY | HCM | FCM\nName \t\t: Kumar S.S\nRol...                 1136   
78  Venkateswarlu.B\t\t\t\t\t\t\t\tWorkday Consult...                  887   
79  Vinay kumar .v\nWorkday Functional Consultant\...                  681   

                                         cleaned_text  cleaned_word_count  \
0                                                 NaN                   1   
1   anubhav kumar singh work globally competitive ...                 753   
2   profile summary 7+ years experience implementi...                 753   
3   peoplesoft database administrator gangareddy p...                 590   
4   murali experience summary 6 years experience w...                 485   
..                                                ...                 ...   
75  workday integration consultant name sri krishn...                 711   
76  seeking suitable positions workday hcm techno ...                 675   
77  workday hcm fcm name kumar s.s role workday co...                 875   
78  venkateswarlu.b workday consultant 5.3 years e...                 658   
79  vinay kumar .v workday functional consultant e...                 507   

                                       gemini_summary  \
0                           No information available.   
1   Anubhav Kumar Singh is a highly experienced Pe...   
2   A highly experienced PeopleSoft DBA with 7+ ye...   
3   A Peoplesoft DBA with 4+ years of experience i...   
4   A Peoplesoft Administrator with 6 years of exp...   
..                                                ...   
75  A Workday Integration Consultant with 4+ years...   
76  A highly experienced Workday HCM Techno-Functi...   
77                                                NaN   
78  A Workday consultant with 5.3 years of experie...   
79                                                NaN   

    gemini_experience_years  gemini_rating  \
0                       NaN            1.0   
1                       7.0            8.0   
2                       7.0            8.0   
3                       4.0            8.0   
4                       6.0            7.0   
..                      ...            ...   
75                      4.5            8.0   
76                      4.0            8.0   
77                      NaN            NaN   
78                      5.3            8.0   
79                      NaN            NaN   

                                      gemini_feedback  
0   No resume content provided; insufficient infor...  
1   Strong technical skills; resume could benefit .

In [29]:
cleaned_data =resume_data.drop(['file_name','text','original_word_count','cleaned_word_count','gemini_summary','gemini_experience_years','gemini_rating','gemini_feedback'],axis=1)

In [30]:
print(cleaned_data)

             category                                       cleaned_text
0          Peoplesoft                                                NaN
1   Peoplesoft Resume  anubhav kumar singh work globally competitive ...
2   Peoplesoft Resume  profile summary 7+ years experience implementi...
3   Peoplesoft Resume  peoplesoft database administrator gangareddy p...
4   Peoplesoft Resume  murali experience summary 6 years experience w...
..                ...                                                ...
75            workday  workday integration consultant name sri krishn...
76            workday  seeking suitable positions workday hcm techno ...
77            workday  workday hcm fcm name kumar s.s role workday co...
78            workday  venkateswarlu.b workday consultant 5.3 years e...
79            workday  vinay kumar .v workday functional consultant e...

[80 rows x 2 columns]


In [31]:
cleaned_data.isnull()

category  cleaned_text
0      False          True
1      False         False
2      False         False
3      False         False
4      False         False
..       ...           ...
75     False         False
76     False         False
77     False         False
78     False         False
79     False         False

[80 rows x 2 columns]

In [32]:
cleaned_data.dropna(inplace=True)

In [33]:
import re
def cleanResume(txt):
    cleanText = re.sub('http\S+\s', ' ', txt)
    cleanText = re.sub('RT|cc', ' ', cleanText)
    cleanText = re.sub('#\S+\s', ' ', cleanText)
    cleanText = re.sub('@\S+', '  ', cleanText)
    cleanText = re.sub('[%s]' % re.escape("""!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~"""), ' ', cleanText)
    cleanText = re.sub(r'[^\x00-\x7f]', ' ', cleanText)
    cleanText = re.sub('\s+', ' ', cleanText)
    return cleanText

In [34]:
cleaned_data['cleaned_text'] = cleaned_data['cleaned_text'].apply(lambda x: cleanResume(x))

In [35]:
cleaned_data

category                                       cleaned_text
1   Peoplesoft Resume  anubhav kumar singh work globally competitive ...
2   Peoplesoft Resume  profile summary 7 years experience implementin...
3   Peoplesoft Resume  peoplesoft database administrator gangareddy p...
4   Peoplesoft Resume  murali experience summary 6 years experience w...
5   Peoplesoft Resume  priyanka ramadoss 6146 mountpleasant coonoor n...
..                ...                                                ...
75            workday  workday integration consultant name sri krishn...
76            workday  seeking suitable positions workday hcm techno ...
77            workday  workday hcm fcm name kumar s s role workday co...
78            workday  venkateswarlu b workday consultant 5 3 years e...
79            workday  vinay kumar v workday functional consultant ex...

[79 rows x 2 columns]

In [36]:
## Label Encoding

In [37]:
from sklearn.preprocessing import LabelEncoder

In [38]:
Le = LabelEncoder()
cleaned_data['LabelEncoding'] = Le.fit_transform(cleaned_data['category'])
cleaned_data

category                                       cleaned_text  \
1   Peoplesoft Resume  anubhav kumar singh work globally competitive ...   
2   Peoplesoft Resume  profile summary 7 years experience implementin...   
3   Peoplesoft Resume  peoplesoft database administrator gangareddy p...   
4   Peoplesoft Resume  murali experience summary 6 years experience w...   
5   Peoplesoft Resume  priyanka ramadoss 6146 mountpleasant coonoor n...   
..                ...                                                ...   
75            workday  workday integration consultant name sri krishn...   
76            workday  seeking suitable positions workday hcm techno ...   
77            workday  workday hcm fcm name kumar s s role workday co...   
78            workday  venkateswarlu b workday consultant 5 3 years e...   
79            workday  vinay kumar v workday functional consultant ex...   

    LabelEncoding  
1               0  
2               0  
3               0  
4               0  
5               0  
..            ...  
75              3  
76              3  
77              3  
78              3  
79              3  

[79 rows x 3 columns]

In [39]:
cleaned_data.describe()

LabelEncoding
count      79.000000
mean        1.455696
std         1.141271
min         0.000000
25%         0.500000
50%         1.000000
75%         3.000000
max         3.000000

In [40]:
cleaned_data.isnull().sum()

category         0
cleaned_text     0
LabelEncoding    0
dtype: int64

In [41]:
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer

In [42]:
x = cleaned_data['cleaned_text'].values
y = cleaned_data['category'].values

In [43]:
x_train , x_test , y_train , y_test = train_test_split(x,y, test_size=0.2, random_state=42)
x_train.shape , y_train.shape , x_test.shape , y_test.shape

((63,), (63,), (16,), (16,))

In [44]:
tfidf_vector = TfidfVectorizer(sublinear_tf=True,stop_words='english')
x_train_tfidf = tfidf_vector.fit_transform(x_train)

In [45]:
x_train_tfidf.shape

(63, 4397)

In [46]:
### Support Vector Machine

In [47]:
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix, accuracy_score,ConfusionMatrixDisplay
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.metrics import f1_score, classification_report, precision_score, recall_score


In [48]:
model_svm = SVC()
model_svm.fit(x_train_tfidf,y_train)

SVC()

In [49]:
prediction = model_svm.predict(x_train_tfidf)
prediction

array(['workday', 'workday', 'SQL Developer', 'React Developer',
       'Peoplesoft Resume', 'workday', 'Peoplesoft Resume',
       'SQL Developer', 'React Developer', 'workday', 'React Developer',
       'SQL Developer', 'Peoplesoft Resume', 'React Developer',
       'SQL Developer', 'workday', 'Peoplesoft Resume', 'SQL Developer',
       'SQL Developer', 'Peoplesoft Resume', 'workday', 'React Developer',
       'SQL Developer', 'Peoplesoft Resume', 'workday',
       'Peoplesoft Resume', 'Peoplesoft Resume', 'React Developer',
       'Peoplesoft Resume', 'workday', 'Peoplesoft Resume',
       'React Developer', 'workday', 'workday', 'SQL Developer',
       'workday', 'Peoplesoft Resume', 'React Developer',
       'React Developer', 'React Developer', 'SQL Developer',
       'React Developer', 'React Developer', 'workday', 'SQL Developer',
       'Peoplesoft Resume', 'React Developer', 'workday', 'workday',
       'workday', 'workday', 'React Developer', 'React Developer',
       'Peop

In [50]:
accuracy_svm = accuracy_score(y_train, prediction)
print('Accuracy of training set : {:.2f}'.format(model_svm.score(x_train_tfidf, y_train)))
# Classification Report
print("Classification Report:")
print(classification_report(y_train, prediction))

Accuracy of training set : 1.00
Classification Report:
                   precision    recall  f1-score   support

Peoplesoft Resume       1.00      1.00      1.00        15
  React Developer       1.00      1.00      1.00        18
    SQL Developer       1.00      1.00      1.00        12
          workday       1.00      1.00      1.00        18

         accuracy                           1.00        63
        macro avg       1.00      1.00      1.00        63
     weighted avg       1.00      1.00      1.00        63



In [51]:
## Random Forest Classifier

In [52]:
from sklearn.ensemble import RandomForestClassifier

In [53]:
model_rf = RandomForestClassifier(n_estimators=200)
model_rf.fit(x_train_tfidf, y_train)

RandomForestClassifier(n_estimators=200)

In [54]:
prediction_rf = model_rf.predict(x_train_tfidf)
prediction_rf

array(['workday', 'workday', 'SQL Developer', 'React Developer',
       'Peoplesoft Resume', 'workday', 'Peoplesoft Resume',
       'SQL Developer', 'React Developer', 'workday', 'React Developer',
       'SQL Developer', 'Peoplesoft Resume', 'React Developer',
       'SQL Developer', 'workday', 'Peoplesoft Resume', 'SQL Developer',
       'SQL Developer', 'Peoplesoft Resume', 'workday', 'React Developer',
       'SQL Developer', 'Peoplesoft Resume', 'workday',
       'Peoplesoft Resume', 'Peoplesoft Resume', 'React Developer',
       'Peoplesoft Resume', 'workday', 'Peoplesoft Resume',
       'React Developer', 'workday', 'workday', 'SQL Developer',
       'workday', 'Peoplesoft Resume', 'React Developer',
       'React Developer', 'React Developer', 'SQL Developer',
       'React Developer', 'React Developer', 'workday', 'SQL Developer',
       'Peoplesoft Resume', 'React Developer', 'workday', 'workday',
       'workday', 'workday', 'React Developer', 'React Developer',
       'Peop

In [55]:
accuracy_rf = accuracy_score(y_train,prediction_rf)
print('Accuracy of training set : {:.2f}'.format(model_rf.score(x_train_tfidf, y_train)))
# Classification Matrix
print("Classification Report:")
print(classification_report(y_train, prediction_rf))

Accuracy of training set : 1.00
Classification Report:
                   precision    recall  f1-score   support

Peoplesoft Resume       1.00      1.00      1.00        15
  React Developer       1.00      1.00      1.00        18
    SQL Developer       1.00      1.00      1.00        12
          workday       1.00      1.00      1.00        18

         accuracy                           1.00        63
        macro avg       1.00      1.00      1.00        63
     weighted avg       1.00      1.00      1.00        63



In [56]:
## Logistic_Regression

In [57]:
from sklearn.linear_model import LogisticRegression

In [58]:
model_lr = LogisticRegression()
model_lr.fit(x_train_tfidf, y_train)
prediction_lr = model_lr.predict(x_train_tfidf)
prediction_lr

array(['workday', 'workday', 'SQL Developer', 'React Developer',
       'Peoplesoft Resume', 'workday', 'Peoplesoft Resume',
       'SQL Developer', 'React Developer', 'workday', 'React Developer',
       'SQL Developer', 'Peoplesoft Resume', 'React Developer',
       'SQL Developer', 'workday', 'Peoplesoft Resume', 'SQL Developer',
       'SQL Developer', 'Peoplesoft Resume', 'workday', 'React Developer',
       'SQL Developer', 'Peoplesoft Resume', 'workday',
       'Peoplesoft Resume', 'Peoplesoft Resume', 'React Developer',
       'Peoplesoft Resume', 'workday', 'Peoplesoft Resume',
       'React Developer', 'workday', 'workday', 'SQL Developer',
       'workday', 'Peoplesoft Resume', 'React Developer',
       'React Developer', 'React Developer', 'SQL Developer',
       'React Developer', 'React Developer', 'workday', 'SQL Developer',
       'Peoplesoft Resume', 'React Developer', 'workday', 'workday',
       'workday', 'workday', 'React Developer', 'React Developer',
       'Peop

In [59]:
accuracy_lr = accuracy_score(y_train,prediction_lr)
print('Accuracy of training set : {:.2f}'.format(model_rf.score(x_train_tfidf, y_train)))
# Classification Matrix
print("Classification Report:")
print(classification_report(y_train, prediction_lr))

Accuracy of training set : 1.00
Classification Report:
                   precision    recall  f1-score   support

Peoplesoft Resume       1.00      1.00      1.00        15
  React Developer       1.00      1.00      1.00        18
    SQL Developer       1.00      1.00      1.00        12
          workday       1.00      1.00      1.00        18

         accuracy                           1.00        63
        macro avg       1.00      1.00      1.00        63
     weighted avg       1.00      1.00      1.00        63



In [60]:
## Pipeline

In [61]:
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer

In [62]:
text_ppl = Pipeline([('tfidf', TfidfVectorizer()),
                     ('model_svm', SVC()),
                     ])
text_ppl.fit(x_train,y_train)

Pipeline(steps=[('tfidf', TfidfVectorizer()), ('model_svm', SVC())])

In [63]:
prediction_ppl = text_ppl.predict(x_test)
prediction_ppl

array(['React Developer', 'Peoplesoft Resume', 'React Developer',
       'React Developer', 'React Developer', 'React Developer',
       'Peoplesoft Resume', 'workday', 'Peoplesoft Resume',
       'Peoplesoft Resume', 'SQL Developer', 'React Developer', 'workday',
       'React Developer', 'workday', 'SQL Developer'], dtype=object)

In [64]:
from sklearn import metrics

In [65]:
print("Classification Report For SVC Model")
print(metrics.classification_report(y_test, prediction_ppl))

Classification Report For SVC Model
                   precision    recall  f1-score   support

Peoplesoft Resume       1.00      0.80      0.89         5
  React Developer       0.86      1.00      0.92         6
    SQL Developer       1.00      1.00      1.00         2
          workday       1.00      1.00      1.00         3

         accuracy                           0.94        16
        macro avg       0.96      0.95      0.95        16
     weighted avg       0.95      0.94      0.94        16



In [66]:
print("Accuracy Score For SVC Model")
print(metrics.accuracy_score(y_test, prediction_ppl))

Accuracy Score For SVC Model
0.9375


In [67]:
print("Confusion matrix For SVC Model")
print(metrics.confusion_matrix(y_test, prediction_ppl))

Confusion matrix For SVC Model
[[4 1 0 0]
 [0 6 0 0]
 [0 0 2 0]
 [0 0 0 3]]


In [68]:
text_ppl_rf = Pipeline([('tfidf', TfidfVectorizer()),
                     ('model_rf', RandomForestClassifier(n_estimators=200)),
                     ])
text_ppl_rf.fit(x_train,y_train)

Pipeline(steps=[('tfidf', TfidfVectorizer()),
                ('model_rf', RandomForestClassifier(n_estimators=200))])

In [69]:
prediction_ppl_rf = text_ppl.predict(x_test)
prediction_ppl_rf

array(['React Developer', 'Peoplesoft Resume', 'React Developer',
       'React Developer', 'React Developer', 'React Developer',
       'Peoplesoft Resume', 'workday', 'Peoplesoft Resume',
       'Peoplesoft Resume', 'SQL Developer', 'React Developer', 'workday',
       'React Developer', 'workday', 'SQL Developer'], dtype=object)

In [70]:
print("Classification Report For Random Forest Model")
print(metrics.classification_report(y_test, prediction_ppl_rf))

Classification Report For Random Forest Model
                   precision    recall  f1-score   support

Peoplesoft Resume       1.00      0.80      0.89         5
  React Developer       0.86      1.00      0.92         6
    SQL Developer       1.00      1.00      1.00         2
          workday       1.00      1.00      1.00         3

         accuracy                           0.94        16
        macro avg       0.96      0.95      0.95        16
     weighted avg       0.95      0.94      0.94        16



In [71]:
print("Accuracy Score For Random Forest Model")
print(metrics.accuracy_score(y_test, prediction_ppl_rf))

Accuracy Score For Random Forest Model
0.9375


In [72]:
print("Confusion matrix For Random Forest Model")
print(metrics.confusion_matrix(y_test, prediction_ppl_rf))

Confusion matrix For Random Forest Model
[[4 1 0 0]
 [0 6 0 0]
 [0 0 2 0]
 [0 0 0 3]]
